export interface Prompt {
  id: string
  imageUrl: string
  title: string
  corePrompt: string
  negativePrompt: string
  model: string
  category: string
  aspectRatio: string
  seed?: number
  steps?: number
  cfgScale?: number
}

export const prompts: Prompt[] = [
  {
    id: '1',
    imageUrl: 'https://images.unsplash.com/photo-1634017839464-5c339bbe3c35?w=800&auto=format&fit=crop&q=80',
    title: 'Cosmic Dreamscape',
    corePrompt: 'ethereal cosmic landscape, swirling nebulas in deep purple and cyan, floating crystalline structures, bioluminescent flora, cinematic lighting, volumetric fog, 8k ultra detailed, artstation trending',
    negativePrompt: 'blurry, low quality, pixelated, watermark, text, logo',
    model: 'Midjourney v6',
    category: 'Landscape',
    aspectRatio: '16:9',
    seed: 42891,
    steps: 50,
    cfgScale: 7.5,
  },
  {
    id: '2',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    title: 'Abstract Geometry',
    corePrompt: 'abstract geometric composition, flowing organic shapes, gradient mesh, soft pastels mixed with bold accents, minimalist design, clean edges, studio lighting',
    negativePrompt: 'noisy, cluttered, photorealistic, faces, text',
    model: 'DALL-E 3',
    category: 'Abstract',
    aspectRatio: '1:1',
    seed: 12847,
    steps: 40,
    cfgScale: 8,
  },
  {
    id: '3',
    imageUrl: 'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?w=800&auto=format&fit=crop&q=80',
    title: 'Neon Metropolis',
    corePrompt: 'cyberpunk cityscape at night, neon signs reflecting on wet streets, towering skyscrapers, flying vehicles, atmospheric fog, blade runner aesthetic, hyper detailed',
    negativePrompt: 'daylight, empty streets, low detail, cartoon style',
    model: 'Stable Diffusion XL',
    category: 'Sci-Fi',
    aspectRatio: '21:9',
    seed: 98234,
    steps: 45,
    cfgScale: 7,
  },
  {
    id: '4',
    imageUrl: 'https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?w=800&auto=format&fit=crop&q=80',
    title: 'Celestial Portrait',
    corePrompt: 'portrait of ethereal being made of stardust, glowing constellation patterns on skin, cosmic backdrop, soft rim lighting, dreamy atmosphere, fine art photography style',
    negativePrompt: 'ugly, deformed, disfigured, poor anatomy, bad hands',
    model: 'Midjourney v6',
    category: 'Portrait',
    aspectRatio: '4:5',
    seed: 55123,
    steps: 50,
    cfgScale: 8.5,
  },
  {
    id: '5',
    imageUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&auto=format&fit=crop&q=80',
    title: 'Fluid Dynamics',
    corePrompt: 'macro photography of colorful liquid art, swirling paint drops in water, vibrant color explosion, high speed capture, pristine white background, commercial quality',
    negativePrompt: 'murky, dark, low saturation, grainy',
    model: 'DALL-E 3',
    category: 'Abstract',
    aspectRatio: '1:1',
    seed: 77456,
    steps: 35,
    cfgScale: 6.5,
  },
  {
    id: '6',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80',
    title: 'Alpine Serenity',
    corePrompt: 'majestic mountain range at golden hour, snow-capped peaks, mirror-like alpine lake, dramatic cloud formations, photorealistic landscape photography, national geographic style',
    negativePrompt: 'oversaturated, hdr effect, artificial looking',
    model: 'Stable Diffusion XL',
    category: 'Landscape',
    aspectRatio: '16:9',
    seed: 33891,
    steps: 40,
    cfgScale: 7,
  },
  {
    id: '7',
    imageUrl: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=800&auto=format&fit=crop&q=80',
    title: 'Minimalist Forms',
    corePrompt: '3D rendered abstract sculpture, smooth organic curves, matte ceramic material, soft shadows, neutral background, museum lighting, contemporary art installation',
    negativePrompt: 'rough texture, harsh shadows, busy background',
    model: 'Midjourney v6',
    category: 'Abstract',
    aspectRatio: '4:5',
    seed: 88912,
    steps: 45,
    cfgScale: 7.5,
  },
  {
    id: '8',
    imageUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&auto=format&fit=crop&q=80',
    title: 'Nebula Core',
    corePrompt: 'deep space nebula photography, stellar nursery, vibrant gas clouds in magenta and teal, scattered stars, hubble telescope style, astronomical wonder, extreme detail',
    negativePrompt: 'earth visible, spacecraft, text overlays',
    model: 'DALL-E 3',
    category: 'Space',
    aspectRatio: '16:9',
    seed: 12098,
    steps: 50,
    cfgScale: 8,
  },
  {
    id: '9',
    imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&auto=format&fit=crop&q=80',
    title: 'Starlit Summit',
    corePrompt: 'mountain peak under milky way, astrophotography, long exposure star trails, snow covered terrain, crystal clear night sky, breathtaking vista, fine art landscape',
    negativePrompt: 'light pollution, cloudy sky, daytime',
    model: 'Stable Diffusion XL',
    category: 'Landscape',
    aspectRatio: '3:2',
    seed: 45672,
    steps: 45,
    cfgScale: 7.5,
  },
  {
    id: '10',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&auto=format&fit=crop&q=80',
    title: 'Digital Renaissance',
    corePrompt: 'classical painting reimagined as digital art, baroque composition with modern elements, rich color palette, dramatic chiaroscuro lighting, museum masterpiece quality',
    negativePrompt: 'flat colors, modern clothing, contemporary setting',
    model: 'Midjourney v6',
    category: 'Art',
    aspectRatio: '4:3',
    seed: 66543,
    steps: 50,
    cfgScale: 9,
  },
  {
    id: '11',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop&q=80',
    title: 'Shadow & Light',
    corePrompt: 'dramatic black and white portrait, strong directional lighting, deep shadows, emotional expression, film noir aesthetic, hasselblad quality, gallery worthy',
    negativePrompt: 'color, flat lighting, snapshot quality',
    model: 'DALL-E 3',
    category: 'Portrait',
    aspectRatio: '4:5',
    seed: 23456,
    steps: 40,
    cfgScale: 7,
  },
  {
    id: '12',
    imageUrl: 'https://images.unsplash.com/photo-1604076913837-52ab5629fba9?w=800&auto=format&fit=crop&q=80',
    title: 'Botanical Dreams',
    corePrompt: 'surreal botanical illustration, oversized exotic flowers, intricate details, watercolor and ink style, vintage scientific illustration influence, soft dreamy palette',
    negativePrompt: 'photorealistic, plain background, simple composition',
    model: 'Stable Diffusion XL',
    category: 'Nature',
    aspectRatio: '1:1',
    seed: 78901,
    steps: 45,
    cfgScale: 8,
  },
]

export const models = ['All Models', 'Midjourney v6', 'DALL-E 3', 'Stable Diffusion XL']
export const categories = ['All Categories', 'Landscape', 'Abstract', 'Sci-Fi', 'Portrait', 'Space', 'Art', 'Nature']
export const aspectRatios = ['All Ratios', '1:1', '4:5', '4:3', '3:2', '16:9', '21:9']
